spring.application.name=file-upload-s3-bucket

aws.region=ap-south-1
aws.s3.bucket-name=i-my-demo-bucket
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}

# Disable caching for development
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false